// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActivities() {
  return window['go']['backend']['Backend']['GetActivities']();
}

export function RemoveActivity(arg1) {
  return window['go']['backend']['Backend']['RemoveActivity'](arg1);
}

export function SetActivity(arg1) {
  return window['go']['backend']['Backend']['SetActivity'](arg1);
}

export function UpdateActivityName(arg1, arg2) {
  return window['go']['backend']['Backend']['UpdateActivityName'](arg1, arg2);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['backend']['Backend']['UploadFile'](arg1, arg2, arg3);
}
