// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetActivities():Promise<Array<backend.Activity>>;

export function RemoveActivity(arg1:number):Promise<void>;

export function SetActivity(arg1:backend.Activity):Promise<void>;

export function UpdateActivityName(arg1:number,arg2:string):Promise<void>;

export function UploadFile(arg1:string,arg2:string,arg3:string):Promise<void>;
